#include <iostream>
#include <Windows.h>

using namespace std;

int main()
{
	int selection = 0;
	//game startup
	Sleep(400);
	cout << "          __________                            ____  ___                                                        ____" << endl;
	Sleep(400);
	cout << "         /__    ___/  ________   ________      /    |/   |     __________     _________   ___   ___   ________  /_  /" << endl;
	Sleep(400);
	cout << "           /   /     /  ___  /  /  _____/     /          |    /  ___    /    /  ___   /  /  /  /  /  /  _____/   /_/ " << endl;
	Sleep(400);
	cout << "          /   /     /  _____/  /  /____      /  /|   /|  |   /  /__/    |   /  /__/  /  /  /__/  /  /_____  /        " << endl;
	Sleep(400);
	cout << "         /___/     /_______>  /_______/     /__/ |__/ |__|  /________/|_|  /_____   /  /________/  /_______/         " << endl;
	Sleep(400);
	cout << "                                                                          ______/  /                                 " << endl;
	Sleep(400);
	cout << "                                                                         /________/                                  " << endl;
	Sleep(400);
	cout << "      ______                                                  ____                                     ____          " << endl;
	Sleep(400);
	cout << "     /  _   |     ________   ________   ____   ________   ___/   /__   __________     __ _______   ___/   /__        " << endl;
	Sleep(400);
	cout << "    /  /_|  |    /  _____/  /  _____/  /   /  /  _____/  /__    ___/  /  ___    /    / // __   /  /__    ___/        " << endl;
	Sleep(400);
	cout << "   /  ___   |   /_____  /  /_____  /  /   /  /_____  /     /   /     /  /__/    |   /    / /  /     /   /            " << endl;
	Sleep(400);
	cout << "  /__/   |__|  /_______/  /_______/  /___/  /_______/     /___/     /________/|_|  /____/ /__/     /___/             " << endl;
	Sleep(400);
	system("color 87");
	Sleep(50);
	system("color f1");
	system("cls");
	Sleep(3000);
	system("color 8f");
	cout << "     +    __________       +           *        ____  ___        *                +        +           *         ____" << endl;
	cout << "         /__    ___/  ________   ________      /    |/   |     __________     _________   ___   ___ . ________ +/_  /" << endl;
	cout << "       .   /   /     /  ___  /  /  _____/     /          |    /  ___    /    /  ___   /  /  /  /  /  /  _____/   /_/ " << endl;
	cout << "    .     /   / +   /  _____/  /  /____   *  /  /|   /|  |   /  /__/    |   /  /__/  /  /  /__/  /  /_____  /  .     " << endl;
	cout << "         /___/     /_______>  /_______/     /__/ |__/ |__|  /________/|_|  /_____   /  /________/  /_______/ .       " << endl;
	cout << "       *       .       .        *       +         .       *               ______/  /            .               .    " << endl;
	cout << "   .                                +                  .         .       /________/     +                 .          " << endl;
	cout << "      ______ .           +                     +              ____     .              .     *          ____     +    " << endl;
	cout << "     /  _   |     ________ . ________   ____ + ________   ___/   /__   __________ *   __ _______ + ___/   /__ .      " << endl;
	cout << "    /  /_|  |    /  _____/  /  _____/. /   /  /  _____/  /__    ___/  /  ___    /    / // __   /  /__    ___/        " << endl;
	cout << "   /  ___   |+  /_____  /  /_____  / ./   /  /_____  /  .  /   /     /  /__/    |   /    / /  /   . /   / .          " << endl;
	cout << "  /__/   |__|  /_______/ +/_______/  /___/  /_______/     /___/   + /________/|_|  /____/ /__/     /___/     *       " << endl;
	cout << " *  .     +          .         *      .          +            .      .          +        .    .        +             " << endl;
	Sleep(500);
	system("color 0f");
	Sleep(1000);
	cout << endl;
	cout << "                                               An educational game about C++                                            " << endl;
	Sleep(3000); 
	cout << endl << endl;
	cout << "                                                   1. N e w   G a m e                                                   " << endl;
	cout << "                                                   2. C o n t i n u e                                                   " << endl;
	cout << "                                                   3.     Q u i t                                                       " << endl;
	Sleep(1000);
	while (selection != 3)
	{
		system("cls");
		cout << "     +    __________       +           *        ____  ___        *                +        +           *         ____" << endl;
		cout << "         /__    ___/  ________   ________      /    |/   |     __________     _________   ___   ___ . ________ +/_  /" << endl;
		cout << "       .   /   /     /  ___  /  /  _____/     /          |    /  ___    /    /  ___   /  /  /  /  /  /  _____/   /_/" << endl;
		cout << "    .     /   / +   /  _____/  /  /____   *  /  /|   /|  |   /  /__/    |   /  /__/  /  /  /__/  /  /_____  /  ." << endl;
		cout << "         /___/     /_______>  /_______/     /__/ |__/ |__|  /________/|_|  /_____   /  /________/  /_______/ ." << endl;
		cout << "       *       .       .        *       +         .       *               ______/  /            .               ." << endl;
		cout << "   .                                +                  .         .       /________/     +                 ." << endl;
		cout << "      ______ .           +                     +              ____     .              .     *          ____     +" << endl;
		cout << "     /  _   |     ________ . ________   ____ + ________   ___/   /__   __________ *   __ _______ + ___/   /__ ." << endl;
		cout << "    /  /_|  |    /  _____/  /  _____/. /   /  /  _____/  /__    ___/  /  ___    /    / // __   /  /__    ___/" << endl;
		cout << "   /  ___   |+  /_____  /  /_____  / ./   /  /_____  /  .  /   /     /  /__/    |   /    / /  /   . /   / ." << endl;
		cout << "  /__/   |__|  /_______/ +/_______/  /___/  /_______/     /___/   + /________/|_|  /____/ /__/     /___/     *" << endl;
		cout << " *  .     +          .         *      .          +            .      .          +        .    .        +" << endl;
		cout << "\n                                               An educational game about C++\n\n" << endl;
		cout << "                                                   1. N e w   G a m e\n";
		cout << "                                                   2. C o n t i n u e\n";
		cout << "                                                   3.     Q u i t\n\n";
		cout << "                                              Enter Number to select option: ";
		cin >> selection;
		
		if (selection == 1)			cout << "OwO";
		else if (selection == 2)	cout << "UwU";
		else if (selection == 3)	break;
		else
		{
			cout << "                                             Error computing...please try again";
			Sleep(1200);
		}
	}

	system("cls");
	cout << "   Game closing";
	Sleep(800);
	cout << ".";
	Sleep(800);
	cout << ".";
	Sleep(800);
	cout << ".";
	Sleep(800);
	return 0;
}



/*int main()
{
	int repeat = 0;
	while (repeat == 0)
	{
		system("pause");
		Beep(698, 500);
		Sleep(140);
		Beep(698, 100);
		Beep(830, 100);
		Beep(932, 100);
		Beep(932, 570);
		Beep(830, 400);
		Sleep(30);
		Beep(698, 500);
		Sleep(15);
		Beep(698, 500);
		Sleep(130);
		Beep(698, 100);
		Beep(830, 100);
		Beep(932, 100);
		Beep(932, 330);
		Beep(830, 330);
		Beep(698, 330);
		Beep(622, 100);
		Beep(698, 100);
		Sleep(710);
		Beep(932, 100);
		Beep(830, 100);
		Beep(698, 100);
		Beep(622, 100);
		Beep(698, 100);
		cout << "exit?" << endl;
		cin >> repeat;
		system("cls");
	}
	
	return 0;
}*/

/*int main()
{
	cout << "Press any key to be nae naed" << endl;
	system("pause");
	system("cls");

	cout << endl;
	cout << "             _:::_" << endl;
	cout << "             *::::" << endl;
	cout << "             _::::" << endl;
	cout << "           _::-::::" << endl;
	cout << "          _::::**:: _" << endl;
	cout << "           _--::::_:::" << endl;
	cout << "          *  _::::::*" << endl;
	cout << "            :::::::::" << endl;
	cout << "           ::::*  :::" << endl;
	cout << "          _:::* _::::" << endl;
	cout << "          :::* ::::" << endl;
	cout << "          :::_ ::::" << endl;
	cout << "           :::: ::::" << endl;
	cout << "            *::: :::" << endl;
	cout << "             ::: :::" << endl;
	cout << "           ::::* *::" << endl;
	cout << "                 _::" << endl;
	cout << "               :::::" << endl;
	Sleep(270);
	system("cls");
	
	cout << endl;
	cout << "         _:::*  ___" << endl;
	cout << "       __::::::::::::" << endl;
	cout << "  _:::::::::::::::::::" << endl;
	cout << ":::           *_:::::_" << endl;
	cout << "              **:::::::_" << endl;
	cout << "             _::::::*:::" << endl;
	cout << "             ::::**:::::" << endl;
	cout << "             ::::  ::::*" << endl;
	cout << "            ::::  :::::" << endl;
	cout << "            ::::  :::" << endl;
	cout << "             :::  ::::" << endl;
	cout << "                  *:::" << endl;
	cout << "                   *::" << endl;
	cout << "                    ::" << endl;
	cout << "                   :::" << endl;
	cout << "                   :::" << endl;
	cout << endl;
	Sleep(270);
	system("cls");

	cout << endl;
	cout << "            _" << endl;
	cout << "           ::::_" << endl;
	cout << "           *:::_" << endl;
	cout << "            *:::___" << endl;
	cout << "            :::::::*:::_" << endl;
	cout << "           ::::::::   :::" << endl;
	cout << "            *::::::_  ::*" << endl;
	cout << "             :::::::::::" << endl;
	cout << "           _::::::::::::" << endl;
	cout << "           :::::**:::::" << endl;
	cout << "           ::::   ::::" << endl;
	cout << "          ::::    :::::" << endl;
	cout << "          *:::_   :::::::_" << endl;
	cout << "           :::*   ****::::::" << endl;
	cout << "            ::          _::" << endl;
	cout << "            :::         **" << endl;
	cout << "          _:::*" << endl;
	Sleep(166);
	system("cls");

	cout << endl;
	cout << "         _:::*  ___" << endl;
	cout << "       __::::::::::::" << endl;
	cout << "  _:::::::::::::::::::" << endl;
	cout << ":::           *_:::::_" << endl;
	cout << "              **:::::::_" << endl;
	cout << "             _::::::*:::" << endl;
	cout << "             ::::**:::::" << endl;
	cout << "             ::::  ::::*" << endl;
	cout << "            ::::  :::::" << endl;
	cout << "            ::::  :::" << endl;
	cout << "             :::  ::::" << endl;
	cout << "                  *:::" << endl;
	cout << "                   *::" << endl;
	cout << "                    ::" << endl;
	cout << "                   :::" << endl;
	cout << "                   :::" << endl;
	cout << endl;
	Sleep(270);
	system("cls");

	cout << endl;
	cout << "            _" << endl;
	cout << "           ::::_" << endl;
	cout << "           *:::_" << endl;
	cout << "            *:::___" << endl;
	cout << "            :::::::*:::_" << endl;
	cout << "           ::::::::   :::" << endl;
	cout << "            *::::::_  ::*" << endl;
	cout << "             :::::::::::" << endl;
	cout << "           _::::::::::::" << endl;
	cout << "           :::::**:::::" << endl;
	cout << "           ::::   ::::" << endl;
	cout << "          ::::    :::::" << endl;
	cout << "          *:::_   :::::::_" << endl;
	cout << "           :::*   ****::::::" << endl;
	cout << "            ::          _::" << endl;
	cout << "            :::         **" << endl;
	cout << "          _:::*" << endl;
	Sleep(183);
	system("cls");

	cout << endl;
	cout << "         _:::*  ___" << endl;
	cout << "       __::::::::::::" << endl;
	cout << "  _:::::::::::::::::::" << endl;
	cout << ":::           *_:::::_" << endl;
	cout << "              **:::::::_" << endl;
	cout << "             _::::::*:::" << endl;
	cout << "             ::::**:::::" << endl;
	cout << "             ::::  ::::*" << endl;
	cout << "            ::::  :::::" << endl;
	cout << "            ::::  :::" << endl;
	cout << "             :::  ::::" << endl;
	cout << "                  *:::" << endl;
	cout << "                   *::" << endl;
	cout << "                    ::" << endl;
	cout << "                   :::" << endl;
	cout << "                   :::" << endl;
	cout << endl;
	Sleep(270);
	system("cls");

	cout << endl;
	cout << "            _" << endl;
	cout << "           ::::_" << endl;
	cout << "           *:::_" << endl;
	cout << "            *:::___" << endl;
	cout << "            :::::::*:::_" << endl;
	cout << "           ::::::::   :::" << endl;
	cout << "            *::::::_  ::*" << endl;
	cout << "             :::::::::::" << endl;
	cout << "           _::::::::::::" << endl;
	cout << "           :::::**:::::" << endl;
	cout << "           ::::   ::::" << endl;
	cout << "          ::::    :::::" << endl;
	cout << "          *:::_   :::::::_" << endl;
	cout << "           :::*   ****::::::" << endl;
	cout << "            ::          _::" << endl;
	cout << "            :::         **" << endl;
	cout << "          _:::*" << endl;
	Sleep(270);
	system("cls");

	cout << endl;
	cout << "            __" << endl;
	cout << "           ::::_        ___---:::" << endl;
	cout << "           *::::::::::::-:::*****" << endl;
	cout << "          _-:::::::::***" << endl;
	cout << "  *::::__-:** *::::::" << endl;
	cout << "   *******    *:::::_" << endl;
	cout << "            -::::::" << endl;
	cout << "            ::::::::" << endl;
	cout << "           -:::::::*" << endl;
	cout << "           ::::::::" << endl;
	cout << "          ::::::::" << endl;
	cout << "         ::::*:::::::_" << endl;
	cout << "        :::**   *::::::_" << endl;
	cout << "       ::_         *:::::_" << endl;
	cout << "      **::           _:::::" << endl;
	cout << "                   -***" << endl;
	Sleep(200);
	system("cls");

	cout << endl;
	cout << "         -::::" << endl;
	cout << "         :::::___" << endl;
	cout << "   	  _:::::::::" << endl;
	cout << "   :::_::-::::::::::" << endl;
	cout << "   *:::::::* :::::::" << endl;
	cout << "             ::::::__" << endl;
	cout << "          _::::::::::" << endl;
	cout << "        _::::::::::::" << endl;
	cout << "       _:::::*  :::::" << endl;
	cout << "      :::::*    ::::*" << endl;
	cout << "      **::__     :::_" << endl;
	cout << "       :::::     ::::" << endl;
	cout << "       **:::      *::" << endl;
	cout << "         :::      _::" << endl;
	cout << "        _:::" << endl;
	cout << "      --::::" << endl;
	Sleep(333);
	system("cls");

	cout << "          __" << endl;
	cout << "         ::::   __  :::" << endl;
	cout << "        :::    :::::  :::__" << endl;
	cout << "       :::------::::__--::::__" << endl;
	cout << "       ******:::::::::::***:::" << endl;
	cout << "             :::::::*" << endl;
	cout << "             :::::::" << endl;
	cout << "             ::::::::" << endl;
	cout << "             -::::::::" << endl;
	cout << "              ::::::::*" << endl;
	cout << "              ::::::::" << endl;
	cout << "              :::::::" << endl;
	cout << "              *::::::" << endl;
	cout << "              *::::::" << endl;
	cout << "                *::*:::_" << endl;
	cout << "                _::   :::_" << endl;
	cout << "                :::  :::**" << endl;
	cout << "               -:::  **" << endl;
	cout << "                **" << endl;
	Sleep(383);
	system("cls");

	cout << endl;
	cout << "               -::-" << endl;
	cout << "               ::::" << endl;
	cout << "            ----::::" << endl;
	cout << "           ::::::::::::" << endl;
	cout << "           ::::::::::::" << endl;
	cout << "           ::::::::::::::" << endl;
	cout << "           :: :::::::::::" << endl;
	cout << "          -:: :::::::: ::-" << endl;
	cout << "         -::  :::::::  :::-" << endl;
	cout << "         *** :::::::   *:::" << endl;
	cout << "            *:::::" << endl;
	cout << "            ::::::::" << endl;
	cout << "            ::*::::" << endl;
	cout << "            ::- **::" << endl;
	cout << "            :::   :::" << endl;
	cout << "                  ::::" << endl;
	cout << "                 -:::*" << endl;
	Sleep(266);
	system("cls");

	cout << endl;
	cout << "               -::" << endl;
	cout << "           __  :::--" << endl;
	cout << "       :::::::::::::::--" << endl;
	cout << "        *-::_  :::::::::::__" << endl;
	cout << "          ::::  ::::::   --:::" << endl;
	cout << "         **::   ::::::  ::-" << endl;
	cout << "              -:::::::::" << endl;
	cout << "              :::::::::-" << endl;
	cout << "              :::::::::" << endl;
	cout << "              :::::*:::*" << endl;
	cout << "              :::::-:**" << endl;
	cout << "              **:::::::" << endl;
	cout << "                :::**:::-" << endl;
	cout << "               _::  --::::" << endl;
	cout << "              ::**" << endl;
	cout << "              ::::" << endl;
	Sleep(250);
	system("cls");

	cout << endl;
	cout << "               -::-" << endl;
	cout << "               ::::" << endl;
	cout << "            ----::::" << endl;
	cout << "           ::::::::::::" << endl;
	cout << "           ::::::::::::" << endl;
	cout << "           ::::::::::::::" << endl;
	cout << "           :: :::::::::::" << endl;
	cout << "          -:: :::::::: ::-" << endl;
	cout << "         -::  :::::::  :::-" << endl;
	cout << "         *** :::::::   *:::" << endl;
	cout << "            *:::::" << endl;
	cout << "            ::::::::" << endl;
	cout << "            ::*::::" << endl;
	cout << "            ::- **::" << endl;
	cout << "            :::   :::" << endl;
	cout << "                  ::::" << endl;
	cout << "                 -:::*" << endl;
	Sleep(300);
	system("cls");

	cout << endl;
	cout << "               -::" << endl;
	cout << "           __  :::--" << endl;
	cout << "       :::::::::::::::--" << endl;
	cout << "        *-::_  :::::::::::__" << endl;
	cout << "          ::::  ::::::   --:::" << endl;
	cout << "         **::   ::::::  ::-" << endl;
	cout << "              -:::::::::" << endl;
	cout << "              :::::::::-" << endl;
	cout << "              :::::::::" << endl;
	cout << "              :::::*:::*" << endl;
	cout << "              :::::-:**" << endl;
	cout << "              **:::::::" << endl;
	cout << "                :::**:::-" << endl;
	cout << "               _::  --::::" << endl;
	cout << "              ::**" << endl;
	cout << "              ::::" << endl;
	Sleep(300);
	system("cls");

	cout << endl;
	cout << "           -::-" << endl;
	cout << "           :::::" << endl;
	cout << "           *:::--" << endl;
	cout << "         -:::::::--" << endl;
	cout << "        -::::::::::-" << endl;
	cout << "       -::* *:::::::-" << endl;
	cout << "      :::    ::::::::" << endl;
	cout << "       -::   ::::::::" << endl;
	cout << "        ***  ::::::::" << endl;
	cout << "             *::::::*" << endl;
	cout << "              ::::::::" << endl;
	cout << "              :::   :::" << endl;
	cout << "               ::: :::" << endl;
	cout << "              :::   :::" << endl;
	cout << "             :::     :::" << endl;
	cout << "            :::       ::::" << endl;
	cout << "           -:::       -:::*" << endl;
	Sleep(700);
	system("cls");

	cout << endl;
	cout << "                -::-" << endl;
	cout << "                ::::" << endl;
	cout << "         :  _-::-::::--_" << endl;
	cout << "      ---:::::**:::::::::::_" << endl;
	cout << "       :::*   **::::::***:::_" << endl;
	cout << "               ::::::-   :::" << endl;
	cout << "              _::::::  :::" << endl;
	cout << "              :::::::: :::" << endl;
	cout << "             :::::::: ***" << endl;
	cout << "             *::::::" << endl;
	cout << "              ::::*" << endl;
	cout << "              :::::_" << endl;
	cout << "              :::::::" << endl;
	cout << "               :::**-::" << endl;
	cout << "               :::   :::" << endl;
	cout << "               :::  :::" << endl;
	cout << "              ::::" << endl;
	cout << "            :::::" << endl;
	Sleep(850);
	system("cls");

	cout << endl;
	cout << "              -::-" << endl;
	cout << "              :::::_" << endl;
	cout << "            _::::::::" << endl;
	cout << "           :::*:::::::" << endl;
	cout << "           ----:::::::" << endl;
	cout << "             :::::::" << endl;
	cout << "            _:::::::_" << endl;
	cout << "            -:::::::::*" << endl;
	cout << "            ::::::::*" << endl;
	cout << "           ::::::::" << endl;
	cout << "           :::::::" << endl;
	cout << "            *:::::-" << endl;
	cout << "             *:::::-" << endl;
	cout << "             _--::::" << endl;
	cout << "            -::: :::" << endl;
	cout << "                _:::" << endl;
	cout << "              ::::::" << endl;
	Sleep(733);
	system("cls");

	cout << "I'm so sorry" << endl;
	Sleep(2000);
	system("cls");
	system("pause");
	return 0;
}*/
